// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDZkBA66R0HwGLE3T3oYHaJVZT0TUiIc',
    appId: '1:374054812120:web:a2bc1800bcbed70ca91aad',
    messagingSenderId: '374054812120',
    projectId: 'retree-firebase-fm',
    authDomain: 'retree-firebase-fm.firebaseapp.com',
    storageBucket: 'retree-firebase-fm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpOYYiass_GoP1LtIsnSo9lnhoHa6j3c',
    appId: '1:374054812120:android:80f12aa1a9f2e83ca91aad',
    messagingSenderId: '374054812120',
    projectId: 'retree-firebase-fm',
    storageBucket: 'retree-firebase-fm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfdF9ZiOvd3EjqqiMd8i5s32ek2nLiuvo',
    appId: '1:374054812120:ios:7afe1af76a54642aa91aad',
    messagingSenderId: '374054812120',
    projectId: 'retree-firebase-fm',
    storageBucket: 'retree-firebase-fm.firebasestorage.app',
    iosBundleId: 'com.example.retree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfdF9ZiOvd3EjqqiMd8i5s32ek2nLiuvo',
    appId: '1:374054812120:ios:7afe1af76a54642aa91aad',
    messagingSenderId: '374054812120',
    projectId: 'retree-firebase-fm',
    storageBucket: 'retree-firebase-fm.firebasestorage.app',
    iosBundleId: 'com.example.retree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSDZkBA66R0HwGLE3T3oYHaJVZT0TUiIc',
    appId: '1:374054812120:web:c3f885806cfcd005a91aad',
    messagingSenderId: '374054812120',
    projectId: 'retree-firebase-fm',
    authDomain: 'retree-firebase-fm.firebaseapp.com',
    storageBucket: 'retree-firebase-fm.firebasestorage.app',
  );

}



